name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Bash test
        run: |
          for i in `seq 1 20`
          do
              echo $i
              echo stderr $i >&2
          done

      - name: Bash with 'stdbuf -i0 -o0 -e0'
        run: |
          stdbuf -i0 -o0 -e0 bash -c 'for i in `seq 1 20`
            do
                echo $i
                echo stderr $i >&2
            done'
